export const rows = [
  {
    id: 1,
    name: "Match",
    description: "Jon",
    category: { id: "1", title: "Category1" },
    totalQuestions: 35,
  },
  {
    id: 2,
    name: "Match",
    description: "Jon",
    category: { id: "1", title: "Category1" },
    totalQuestions: 35,
  },
  {
    id: 3,
    name: "Match",
    description: "Jon",
    category: { id: "1", title: "Category1" },
    totalQuestions: 35,
  },
  {
    id: 4,
    name: "Match",
    description: "Jon",
    category: { id: "1", title: "Category1" },
    totalQuestions: 35,
  },
  {
    id: 5,
    name: "Match",
    description: "Jon",
    category: { id: "1", title: "Category1" },
    totalQuestions: 35,
  },
  {
    id: 6,
    name: "Match",
    description: "Jon",
    category: { id: "1", title: "Category1" },
    totalQuestions: 35,
  },
  {
    id: 7,
    name: "Match",
    description: "Jon",
    category: { id: "1", title: "Category1" },
    totalQuestions: 35,
  },
  {
    id: 8,
    name: "Match",
    description: "Jon",
    category: { id: "1", title: "Category1" },
    totalQuestions: 35,
  },
  {
    id: 9,
    name: "Match",
    description: "Jon",
    category: { id: "1", title: "Category1" },
    totalQuestions: 35,
  },
  {
    id: 0,
    name: "Match",
    description: "Jon",
    category: { id: "1", title: "Category1" },
    totalQuestions: 35,
  },
  {
    id: 11,
    name: "Match",
    description: "Jon",
    category: { id: "1", title: "Category1" },
    totalQuestions: 35,
  },
  {
    id: 12,
    name: "Match",
    description: "Jon",
    category: { id: "1", title: "Category1" },
    totalQuestions: 35,
  },
  {
    id: 13,
    name: "Match",
    description: "Jon",
    category: { id: "1", title: "Category1" },
    totalQuestions: 35,
  },
  {
    id: 14,
    name: "Match",
    description: "Jon",
    category: { id: "1", title: "Category1" },
    totalQuestions: 35,
  },
  {
    id: 15,
    name: "Match",
    description: "Jon",
    category: { id: "1", title: "Category1" },
    totalQuestions: 35,
  },
];
